apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mongo-deployment.yml
- mongo-service.yml
- rabbit-deployment.yml
- rabbit-service.yml
- crawler-deployment.yml
- crawler-service.yml
- ui-deployment.yml
- ui-service.yml
- ui-ingress.yml
- application-ns.yml
images:
- name: mongo_image
  newName: mongo
  newTag: 4.0.18
- name: rabbit_image
  newName: rabbitmq
  newTag: "3-management"
