{
 "title": "crawler dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Число обработанных станиц",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crawler_pages_parsed{}",
     "legendFormat": "Кол-во обработанных ботом страниц $namespace"
    }
   ]
  },
  {
   "title": "Engine -  время разбора страницы",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawler_page_parse_time_bucket",
     "legendFormat": "Время затраченное ботом на обработку содержимого веб-страницы за минуту $namespace"
    }
   ]
  },
  {
   "title": "Engine - Среднее время парсинга страницы за час",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_page_parse_time_bucket[5m])) by (le))",
     "legendFormat": "Среднее время получения страницы "
    }
   ]
  },
  {
   "title": " UI -  Количество обработанных запросов за час",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(web_pages_served [1h])",
     "legendFormat": "Кол-во обработанных запросов за час"
    }
   ]
  },
  {
   "title": " UI -  Среднее время генерации страницы",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(web_page_gen_time_bucket[5m])) by (le))",
     "legendFormat": "Среднее время генерации страницы за минуту $namespace"
    }
   ]
  }
 ]
}