version: '3.3'
services:
  prometheus:
    image: ${USER_NAME}/crawler_prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - net_back
      - prometheus_net

  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - prometheus_net
      - net_back
      - net_front


  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - net_back
      - net_front

  mongo-exporter:
    image: ${USER_NAME}/crawler_mongodb_exporter:latest
    networks:
      - net_back
      - net_front
    environment:
      MONGODB_URI: "mongodb://crawlerdb:27017"

  rabbit-exporter:
    image: ${USER_NAME}/crawler_rabbit_exporter:latest
    networks:
      - net_back
      - net_front

  cadvisor:
    image: gcr.io/google_containers/cadvisor:v0.36.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - prometheus_net

volumes:
  prometheus_data:
#  grafana_data:

networks:
    net_back:
    net_front:
    prometheus_net:
