server:

  http_listen_port: 9080
  grpc_listen_port: 0

positions:

  filename: /tmp/positions.yaml

client:

  url: http://loki:3100/loki/api/v1/push
  

scrape_configs:

  - job_name: system
    entry_parser: raw
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*.log

  - job_name: containers
    entry_parser: docker
    static_configs:
    - targets:
        - localhost
    file_sd_configs:
    - files:
      - /etc/promtail/promtail-targets.yaml
    relabel_configs:
    - source_labels: [__address__]
      target_label: container_id
    - source_labels: [container_id]
      target_label: __path__
      replacement: /var/lib/docker/containers/$1*/*.log
