---
global:
  scrape_interval: '5s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'ui'
    static_configs:
      - targets:
        - 'ui:8000'

  - job_name: 'engine'
    static_configs:
      - targets:
        - 'engine:8000'

  - job_name: 'mongo'
    static_configs:
      - targets:
        - 'mongo-exporter:9216'

  - job_name: 'rabbitmq'
    static_configs:
      - targets:
        - 'rabbit-exporter:9419'


  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'cadvisor:8080'
