# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Тесты исходного кода

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies search_engine_crawler
      working-directory: src/search_engine_crawler
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-test.txt
    - name: Test search_engine_crawler 
      working-directory: src/search_engine_crawler
      run: |
        python -m unittest discover -s tests/ 
    - name: Install dependencies search_engine_ui
      working-directory: src/search_engine_ui
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-test.txt
    - name: Test search_engine_ui 
      working-directory: src/search_engine_ui
      run: |
        python -m unittest discover -s tests/ 
