
on:
  push:
    branches: [ test_notif ]
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: "Бот сборочного конвеера" 
        SLACK_TITLE: "Сборка завершена" 
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Сборка завершена {0} '  ${{ job.status }} 'смотри логи' 
 #       SLACK_MESSAGE: format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat')
        SLACK_FOOTER: "OTUS GHA BOT"
